### ISSUE TITLE
Custom token anchoring to avoid using a long prompt

### ISSUE THREAD

**Issue by wiiiktor** [teticio/llama-squad#10]
You are using a pretty long prompt when training the model. You mention Prefix Tuning is used in your training -> does it mean that the prompt can be skipped during inference and it is enough to use the prefix token? (Sorry, I am not familiar with the prefix tuning in practice, never used it in my projects).

**Comment by teticio** [comment]
No, the prompt has to be processed during inference. The prefix tuning just focuses the model on the specialized task without destroying too much the general capabilities it has.
