### ISSUE TITLE
Decoder gap-filling possible

### ISSUE THREAD

**Issue by wiiiktor** [teticio/llama-squad#11]
There is a T5 model that has been trained in a gap-fililng mode and works quite well for this task. This is a prefix-LM, meaning it is somewhat encoder in nature (pages 16-17 of their paper), but this is only about the input/question; it does not really matter, as encoder is not used for answer, so standard decoder architecture could achieve the same, if only trained with mask tokens. 

The graphic below illustrates a few methods of training that they tried (paper: https://arxiv.org/pdf/1910.10683 table 3, page 21): 

<img width="980" alt="image" src="https://github.com/user-attachments/assets/391248f8-986a-4ee2-b656-b3dd5b3631aa">

**Comment by teticio** [comment]
Thanks, yes it is interesting to compare encoders, decoders and encoder-decoders. I'm not convinced that encoder-decoders convey much advantage over pure decoders, and I think there are more and better open source decoders available these days, probably because they are more usable out of the box.
