### ISSUE TITLE
index -1 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by omeruth** [teticio/llama-squad#3]
If I try using openlm-research/open_llama_3b_v2 I get the following error. Any idea

  File "llama-squad/llama_squad.py", line 13, in __call__
    answer_start = torch.where(label == self.answer_start_token_id)[0][-1]
IndexError: index -1 is out of bounds for dimension 0 with size 0

**Comment by teticio** [comment]
If your context window is not large enough to fit the whole training example, it will fail as it won't find the start of the answer (as it doesn't fit). Not a very helpful error message, sorry.
