### ISSUE TITLE
Checkpoints for trained models

### ISSUE THREAD

**Issue by joanvelja** [teticio/llama-squad#6]
Dear @teticio ,

Thanks a lot for the great repo! I was just wondering if it would be possible to release checkpoints for the finetuned models, so to allow experimentation with this baseline model without having to fine-tune it on my own.

Best,

Joan

**Comment by teticio** [comment]
Hi! Thanks for the suggestion and sorry for the delay. I have added one pre-trained adapter so far and plan to add a few others. You can now do

```
python app.py --adapter_name=teticio/llama_3_8b_5_blah_ns
```

for example.
