### ISSUE TITLE
Question about the "Blah blah blah" part

### ISSUE THREAD

**Issue by Deep1994** [teticio/llama-squad#8]
Hello! Thank you for your excellent work! I am very interested in the "Blah blah blah" part you mentioned. If I understand correctly, it means that introducing these special tokens during training will give the model implicit reasoning capabilities, i.e., think before speak/generate? I wonder if there are experiments related to this part in your code? I would like to try out their magic. Thank you very much for your code repository!

**Comment by teticio** [comment]
Hi, yes that is the idea. If you look at the table closely, you will see some experiments with a number of blah tokens and others without.
